/**
 * University Options Configuration
 *
 * Comprehensive list of universities and institutions for Paris and London.
 * Organized by city with alphabetically sorted options.
 */

export interface UniversityOption {
  value: string;
  label: string;
}

export interface CityUniversityGroup {
  city: string;
  label: string;
  options: UniversityOption[];
}

// Paris Universities and Institutions
const PARIS_UNIVERSITIES: UniversityOption[] = [
  { value: 'agroparistech', label: 'AgroParisTech' },
  { value: 'american-business-school', label: 'American Business School Paris' },
  { value: 'american-university-paris', label: 'American University of Paris' },
  { value: 'arts-et-metiers', label: 'Arts et Métiers ParisTech' },
  { value: 'assas', label: 'Assas - Panthéon-Assas University (Paris II)' },
  { value: 'cea', label: 'CEA (French Alternative Energies and Atomic Energy Commission)' },
  { value: 'celsa', label: 'CELSA - École des hautes études en sciences de l\'information et de la communication' },
  { value: 'centrale-supelec', label: 'CentraleSupélec' },
  { value: 'cergy-paris', label: 'CY Cergy Paris Université' },
  { value: 'chimie-paristech', label: 'Chimie ParisTech' },
  { value: 'dauphine', label: 'Dauphine - PSL (Paris Sciences et Lettres)' },
  { value: 'ebs-paris', label: 'EBS Paris - European Business School' },
  { value: 'ecam-epmi', label: 'ECAM-EPMI' },
  { value: 'ecole-42', label: 'École 42' },
  { value: 'ecole-boulle', label: 'École Boulle' },
  { value: 'ecole-camondo', label: 'École Camondo' },
  { value: 'ecole-du-louvre', label: 'École du Louvre' },
  { value: 'ecole-estienne', label: 'École Estienne' },
  { value: 'ecole-hoteliere-paris', label: 'École Hôtelière de Paris' },
  { value: 'ecole-normale-superieure', label: 'École Normale Supérieure (ENS)' },
  { value: 'ecole-polytechnique', label: 'École Polytechnique' },
  { value: 'ecole-ponts', label: 'École des Ponts ParisTech' },
  { value: 'ecole-pratique-hautes-etudes', label: 'École Pratique des Hautes Études' },
  { value: 'edhec-paris', label: 'EDHEC Business School - Paris Campus' },
  { value: 'efap', label: 'EFAP - École des nouveaux métiers de la communication' },
  { value: 'efrei-paris', label: 'EFREI Paris' },
  { value: 'ehesp', label: 'EHESP - École des hautes études en santé publique' },
  { value: 'ehess', label: 'EHESS - École des hautes études en sciences sociales' },
  { value: 'eigsi', label: 'EIGSI - École d\'Ingénieurs en Génie des Systèmes Industriels' },
  { value: 'eiml-paris', label: 'EIML Paris' },
  { value: 'em-normandie-paris', label: 'EM Normandie - Paris Campus' },
  { value: 'emlv', label: 'EMLV - École de Management Léonard de Vinci' },
  { value: 'enpc', label: 'ENPC - École Nationale des Ponts et Chaussées' },
  { value: 'ensae', label: 'ENSAE Paris' },
  { value: 'ensapc', label: 'ENSAPC - École Nationale Supérieure d\'Architecture Paris-Conflans' },
  { value: 'ensba', label: 'ENSBA - École Nationale Supérieure des Beaux-Arts' },
  { value: 'ensg', label: 'ENSG - École Nationale des Sciences Géographiques' },
  { value: 'ensmp', label: 'ENSMP - Mines ParisTech' },
  { value: 'ensta-paris', label: 'ENSTA Paris' },
  { value: 'ephe', label: 'EPHE - École Pratique des Hautes Études' },
  { value: 'epita', label: 'EPITA' },
  { value: 'epitech-paris', label: 'Epitech Paris' },
  { value: 'esam', label: 'ESAM - École Supérieure d\'Arts et Métiers' },
  { value: 'esce', label: 'ESCE International Business School' },
  { value: 'escp-europe', label: 'ESCP Europe' },
  { value: 'esiee-paris', label: 'ESIEE Paris' },
  { value: 'eslsca', label: 'ESLSCA Business School Paris' },
  { value: 'esme-sudria', label: 'ESME Sudria' },
  { value: 'espci', label: 'ESPCI Paris - PSL' },
  { value: 'essca-paris', label: 'ESSCA School of Management - Paris Campus' },
  { value: 'essec', label: 'ESSEC Business School' },
  { value: 'estaca', label: 'ESTACA' },
  { value: 'eurecom', label: 'EURECOM' },
  { value: 'excelia-paris', label: 'Excelia Business School - Paris Campus' },
  { value: 'formations-musique-paris', label: 'Formations Musique Paris' },
  { value: 'glion-paris', label: 'Glion Institute of Higher Education - Paris Campus' },
  { value: 'grenoble-em-paris', label: 'Grenoble École de Management - Paris Campus' },
  { value: 'hec-paris', label: 'HEC Paris' },
  { value: 'ieseg-paris', label: 'IÉSEG School of Management - Paris Campus' },
  { value: 'iesa', label: 'IESA Arts & Culture' },
  { value: 'ifp-school', label: 'IFP School' },
  { value: 'inalco', label: 'INALCO - Institut National des Langues et Civilisations Orientales' },
  { value: 'inseec-paris', label: 'INSEEC Business School - Paris' },
  { value: 'insep', label: 'INSEP - Institut National du Sport, de l\'Expertise et de la Performance' },
  { value: 'institut-catholique-paris', label: 'Institut Catholique de Paris' },
  { value: 'institut-curie', label: 'Institut Curie' },
  { value: 'institut-mines-telecom', label: 'Institut Mines-Télécom' },
  { value: 'institut-optique', label: 'Institut d\'Optique Graduate School' },
  { value: 'ipag-paris', label: 'IPAG Business School - Paris' },
  { value: 'ipesup', label: 'IPESUP - Institut de Préparation aux Études Supérieures' },
  { value: 'isep', label: 'ISEP - Institut Supérieur d\'Électronique de Paris' },
  { value: 'isit', label: 'ISIT - Institut de Management et de Communication Interculturels' },
  { value: 'isth', label: 'ISTH - Institut Supérieur du Tourisme, de l\'Hôtellerie et de l\'Alimentation' },
  { value: 'kedge-paris', label: 'KEDGE Business School - Paris Campus' },
  { value: 'le-cordon-bleu-paris', label: 'Le Cordon Bleu Paris' },
  { value: 'leonard-de-vinci', label: 'Pôle Universitaire Léonard de Vinci' },
  { value: 'neoma-paris', label: 'NEOMA Business School - Paris Campus' },
  { value: 'paris-1-pantheon-sorbonne', label: 'Paris 1 Panthéon-Sorbonne' },
  { value: 'paris-8', label: 'Paris 8 Vincennes-Saint-Denis' },
  { value: 'paris-cite', label: 'Paris Cité (formerly Paris Diderot - Paris 7 & Paris Descartes - Paris 5)' },
  { value: 'paris-dauphine', label: 'Paris Dauphine University - PSL' },
  { value: 'paris-est-creteil', label: 'Paris-Est Créteil University (UPEC)' },
  { value: 'paris-est-marne', label: 'Paris-Est Marne-la-Vallée University (UPEM)' },
  { value: 'paris-nanterre', label: 'Paris Nanterre University (Paris X)' },
  { value: 'paris-nord', label: 'Paris Nord - Sorbonne Paris Nord (Paris XIII)' },
  { value: 'paris-saclay', label: 'Paris-Saclay University' },
  { value: 'parsons-paris', label: 'Parsons Paris - The New School' },
  { value: 'psl', label: 'PSL - Paris Sciences et Lettres University' },
  { value: 'rennes-sb-paris', label: 'Rennes School of Business - Paris Campus' },
  { value: 'sciences-po', label: 'Sciences Po Paris' },
  { value: 'skema-paris', label: 'SKEMA Business School - Paris Campus' },
  { value: 'sorbonne-nouvelle', label: 'Sorbonne Nouvelle (Paris 3)' },
  { value: 'sorbonne-paris-nord', label: 'Sorbonne Paris Nord' },
  { value: 'sorbonne-university', label: 'Sorbonne University' },
  { value: 'strate-ecole-design', label: 'Strate - École de Design' },
  { value: 'telecom-paris', label: 'Télécom Paris' },
  { value: 'toulouse-bs-paris', label: 'Toulouse Business School - Paris Campus' },
  { value: 'universite-paris-saclay', label: 'Université Paris-Saclay' },
  { value: 'up-est-sup', label: 'Université Paris-Est-Sup' },
  { value: 'y-schools', label: 'Y SCHOOLS (formerly ESAM)' },
];

// London Universities and Institutions
const LONDON_UNIVERSITIES: UniversityOption[] = [
  { value: 'arden-university', label: 'Arden University' },
  { value: 'birkbeck', label: 'Birkbeck, University of London' },
  { value: 'bournemouth-university-london', label: 'Bournemouth University London' },
  { value: 'brunel-university', label: 'Brunel University London' },
  { value: 'cass-business-school', label: 'Bayes Business School (formerly Cass)' },
  { value: 'central-saint-martins', label: 'Central Saint Martins' },
  { value: 'city-university', label: 'City, University of London' },
  { value: 'conservatoire-dance-drama', label: 'Conservatoire for Dance and Drama' },
  { value: 'courtauld-institute', label: 'Courtauld Institute of Art' },
  { value: 'coventry-university-london', label: 'Coventry University London' },
  { value: 'cranfield-university', label: 'Cranfield University' },
  { value: 'east-london', label: 'University of East London' },
  { value: 'goldsmiths', label: 'Goldsmiths, University of London' },
  { value: 'greenwich', label: 'University of Greenwich' },
  { value: 'gsm-london', label: 'GSM London' },
  { value: 'guildhall-school', label: 'Guildhall School of Music and Drama' },
  { value: 'heythrop-college', label: 'Heythrop College' },
  { value: 'hult-london', label: 'Hult International Business School - London' },
  { value: 'icp-london', label: 'ICP - International College Portsmouth London Campus' },
  { value: 'imperial-college', label: 'Imperial College London' },
  { value: 'institute-cancer-research', label: 'Institute of Cancer Research' },
  { value: 'judge-business-school', label: 'Judge Business School' },
  { value: 'king-college', label: 'King\'s College London' },
  { value: 'kingston-university', label: 'Kingston University' },
  { value: 'leeds-arts-university-london', label: 'Leeds Arts University - London Campus' },
  { value: 'ley-london', label: 'LEY - London School of Economics for Young People' },
  { value: 'lbs', label: 'London Business School' },
  { value: 'lcf', label: 'London College of Fashion' },
  { value: 'london-film-school', label: 'London Film School' },
  { value: 'london-met', label: 'London Metropolitan University' },
  { value: 'london-school-hygiene', label: 'London School of Hygiene & Tropical Medicine' },
  { value: 'london-south-bank', label: 'London South Bank University' },
  { value: 'lse', label: 'London School of Economics and Political Science (LSE)' },
  { value: 'middlesex-university', label: 'Middlesex University' },
  { value: 'new-college-humanities', label: 'New College of the Humanities' },
  { value: 'northumbria-london', label: 'Northumbria University London Campus' },
  { value: 'point-blank', label: 'Point Blank Music School' },
  { value: 'queen-mary', label: 'Queen Mary University of London' },
  { value: 'ravensbourne-university', label: 'Ravensbourne University London' },
  { value: 'regents-university', label: 'Regent\'s University London' },
  { value: 'richmond-university', label: 'Richmond, The American International University in London' },
  { value: 'roehampton', label: 'University of Roehampton' },
  { value: 'royal-academy-dramatic-art', label: 'Royal Academy of Dramatic Art (RADA)' },
  { value: 'royal-academy-music', label: 'Royal Academy of Music' },
  { value: 'royal-agricultural-university', label: 'Royal Agricultural University' },
  { value: 'royal-college-art', label: 'Royal College of Art' },
  { value: 'royal-college-music', label: 'Royal College of Music' },
  { value: 'royal-holloway', label: 'Royal Holloway, University of London' },
  { value: 'royal-veterinary-college', label: 'Royal Veterinary College' },
  { value: 'soas', label: 'SOAS University of London' },
  { value: 'st-georges', label: 'St George\'s, University of London' },
  { value: 'st-marys-twickenham', label: 'St Mary\'s University, Twickenham' },
  { value: 'the-courtauld', label: 'The Courtauld Institute of Art' },
  { value: 'trinity-laban', label: 'Trinity Laban Conservatoire of Music and Dance' },
  { value: 'ual', label: 'University of the Arts London' },
  { value: 'ucl', label: 'University College London (UCL)' },
  { value: 'university-law-london', label: 'University of Law - London' },
  { value: 'university-west-london', label: 'University of West London' },
  { value: 'university-westminster', label: 'University of Westminster' },
  { value: 'ashridge', label: 'Ashridge Executive Education at Hult' },
  { value: 'bpp-university', label: 'BPP University' },
  { value: 'le-cordon-bleu-london', label: 'Le Cordon Bleu London' },
  { value: 'london-college-communication', label: 'London College of Communication' },
  { value: 'london-college-contemporary-arts', label: 'London College of Contemporary Arts' },
  { value: 'london-interdisciplinary-school', label: 'London Interdisciplinary School' },
  { value: 'london-school-architecture', label: 'London School of Architecture' },
  { value: 'london-school-business-finance', label: 'London School of Business and Finance' },
  { value: 'rosa-parks-university', label: 'UCEM - University College of Estate Management' },
  { value: 'sae-institute-london', label: 'SAE Institute London' },
  { value: 'school-oriental-african-studies', label: 'School of Oriental and African Studies (SOAS)' },
  { value: 'school-pharmacy', label: 'UCL School of Pharmacy' },
  { value: 'the-british-school-osteopathy', label: 'The British School of Osteopathy' },
  { value: 'the-london-institute', label: 'The London Institute of Banking & Finance' },
  { value: 'trocadero-arts', label: 'Trocadero Arts' },
  { value: 'warwick-london', label: 'University of Warwick - London Campus' },
  { value: 'west-thames-college', label: 'West Thames College' },
  { value: 'wimbledon-college-arts', label: 'Wimbledon College of Arts' },
  { value: 'writtle-university-college', label: 'Writtle University College' },
  { value: 'acting-international', label: 'Acting International' },
  { value: 'academy-contemporary-music', label: 'Academy of Contemporary Music' },
  { value: 'arts-educational-schools', label: 'Arts Educational Schools London' },
  { value: 'british-college-osteopathic-medicine', label: 'British College of Osteopathic Medicine' },
  { value: 'british-school-commerce', label: 'British School of Commerce' },
  { value: 'cambridge-school-visual', label: 'Cambridge School of Visual & Performing Arts - London' },
  { value: 'chelsea-college-arts', label: 'Chelsea College of Arts' },
  { value: 'ealing-studios', label: 'Ealing Studios' },
  { value: 'escp-london', label: 'ESCP Business School - London Campus' },
  { value: 'eu-business-school-london', label: 'EU Business School - London' },
  { value: 'european-school-economics', label: 'European School of Economics' },
  { value: 'fashion-retail-academy', label: 'Fashion Retail Academy' },
  { value: 'global-banking-school', label: 'Global Banking School' },
  { value: 'hult-ashridge', label: 'Hult Ashridge Executive Education' },
  { value: 'istituto-marangoni-london', label: 'Istituto Marangoni - London' },
  { value: 'london-academy-music', label: 'London Academy of Music and Dramatic Art (LAMDA)' },
  { value: 'metfilm-school', label: 'MetFilm School' },
  { value: 'musicians-institute-london', label: 'Musicians Institute London' },
  { value: 'other', label: 'Other university (not listed)' },
];

// University options grouped by city
export const UNIVERSITY_OPTIONS: CityUniversityGroup[] = [
  {
    city: 'Paris',
    label: 'Paris Universities',
    options: PARIS_UNIVERSITIES,
  },
  {
    city: 'London',
    label: 'London Universities',
    options: LONDON_UNIVERSITIES,
  },
];

/**
 * Get university options for a specific city
 * @param city - The city name ('Paris' or 'London')
 * @returns Array of university options for the specified city
 */
export function getUniversityOptionsByCity(city: string): UniversityOption[] {
  const cityGroup = UNIVERSITY_OPTIONS.find((group) => group.city === city);
  return cityGroup?.options || [];
}

/**
 * Get all available cities
 * @returns Array of city names
 */
export function getAvailableCities(): string[] {
  return UNIVERSITY_OPTIONS.map((group) => group.city);
}
